### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Sans le slash à la fin de l'url, on obtient un [status code] 403 [reason phrase] Forbidden

### CODE REVIEW

**Comment by sroze** [comment]
Based on [their API documentation about this method](https://api.ovh.com/console/#/sms/%7BserviceName%7D/users/%7Blogin%7D/jobs#POST) there is no trailing slash on this URL.

Moreover, if you had a 404 I'd have a deeper look but with a 403 it's clearly not the source of the problem, you should have a look to your API credentials.

**Comment by sroze** [comment]
@coopTilleuls, to be closed.

**Comment by meyerbaptiste** [comment]
I'm agree with @sroze, I close.

**Comment by ghost** [comment]
I agree.
My mistake is because i use this OVH tutorial : https://www.ovh.com/fr/g1639.envoyer_des_sms_avec_lapi_ovh_en_php
and in this tutorial they use this url (with slash) : https://eu.api.ovh.com/createToken/?GET=/sms/&GET=/sms/*/jobs/&POST=/sms/*/jobs/  to create the API Key

Sorry, and really thanks for this nice bundle ;-)

**Pull request closed without merging**
